DROP TABLE IF EXISTS blog;

CREATE TABLE blog (
  b_id INT(3) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  b_title VARCHAR(50) NOT NULL,
  b_date DATE NOT NULL,
  b_content TEXT(65535),
  b_visible TINYINT(1) NOT NULL,
  b_like INT(3) NOT NULL,
  b_dislike INT(3) NOT NULL
);

INSERT INTO blog
  (b_title, b_date, b_content, b_visible, b_like, b_dislike)
VALUES
  ('Blog Article 1', '2016-10-03',
    '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at posuere odio. Nam varius leo eget mauris vehicula maximus. Suspendisse vestibulum elementum turpis. Sed eget dui ac ante consequat dapibus eu vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean non quam ligula. Nam ultrices ultricies nunc, id blandit magna iaculis vel. Pellentesque consequat malesuada diam nec lacinia. Donec sagittis purus sed sem luctus, eget tempor nibh pretium. Sed malesuada diam quis nisi gravida gravida. Praesent diam turpis, blandit a dignissim in, ultrices a neque. Nunc lacus ligula, egestas quis placerat sed, maximus eget nisi. Proin sit amet nulla in nunc vestibulum vestibulum. Praesent euismod hendrerit odio, ac commodo neque auctor eget. Morbi iaculis urna mauris, vel vehicula nunc convallis mattis. Aliquam ut pulvinar nisl, sed tincidunt mi.</p>

<p>Morbi ultrices faucibus massa a faucibus. Pellentesque nisi lectus, sodales ac dui sit amet, placerat iaculis risus. Praesent tellus ex, aliquet at tellus ac, consectetur dignissim nisl. Nullam euismod efficitur ex sit amet vehicula. In dignissim augue risus, at commodo lacus porttitor a. Ut pharetra mauris non massa placerat, in imperdiet orci ornare. Duis ac varius nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum ac justo ac sollicitudin. Sed elementum sodales hendrerit. Donec rutrum ligula sit amet massa suscipit, ac bibendum tellus gravida. Integer interdum rutrum eleifend. Nam facilisis elit sit amet est molestie auctor. Nulla sed gravida ipsum.</p>

<p>Fusce cursus nulla at augue molestie pretium. Nam ac porta nisl. Donec dapibus dapibus varius. Etiam imperdiet felis sed auctor condimentum. Vivamus nec ullamcorper augue. Curabitur vel fermentum sapien. Etiam lorem erat, viverra at cursus id, egestas ac augue. Fusce vitae dolor sem. Vestibulum finibus, metus id ultricies bibendum, lacus purus condimentum augue, pretium tempus orci odio vel massa. Aenean non quam scelerisque lorem consectetur vulputate non et metus. Morbi interdum ullamcorper fermentum. In tristique vulputate porttitor. Nam elementum placerat est cursus consequat.</p>

<p>Proin bibendum rhoncus lacus, vitae consectetur magna lobortis quis. Mauris sagittis nunc eu sollicitudin semper. Donec dignissim aliquam turpis, quis ornare leo auctor vitae. Fusce sem lacus, euismod eget magna vitae, mattis condimentum neque. Integer tempor metus nec lacus imperdiet faucibus. Integer placerat sem ut urna feugiat vehicula. Sed tincidunt dolor quis eros convallis, quis convallis est consectetur. Vivamus hendrerit congue tempor. Donec elementum sem blandit nunc convallis, ac blandit quam viverra. In vel nulla tincidunt, placerat diam quis, pulvinar lorem.</p>

<p>Maecenas et tortor ante. Mauris sed ullamcorper nisl. Fusce leo lectus, bibendum sed orci vel, efficitur placerat risus. Pellentesque commodo nisi orci, nec convallis tortor viverra id. In hac habitasse platea dictumst. Nullam at sapien odio. Nulla vitae tristique mi. Phasellus pretium nibh quis tellus egestas, et pulvinar lectus pulvinar. Nam dapibus sit amet enim sed dapibus. Duis luctus, neque quis tincidunt volutpat, arcu erat eleifend arcu, a tincidunt lectus turpis ut felis. Nullam sed justo sagittis, convallis velit sed, gravida odio. Praesent faucibus risus odio. Proin fermentum massa velit, ut vulputate lectus semper non. Nunc lectus sapien, viverra ac ante viverra, vestibulum hendrerit diam.</p>',
    1, 0, 0),
  ('Blog Article 2', '2016-9-11',
    '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at posuere odio. Nam varius leo eget mauris vehicula maximus. Suspendisse vestibulum elementum turpis. Sed eget dui ac ante consequat dapibus eu vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean non quam ligula. Nam ultrices ultricies nunc, id blandit magna iaculis vel. Pellentesque consequat malesuada diam nec lacinia. Donec sagittis purus sed sem luctus, eget tempor nibh pretium. Sed malesuada diam quis nisi gravida gravida. Praesent diam turpis, blandit a dignissim in, ultrices a neque. Nunc lacus ligula, egestas quis placerat sed, maximus eget nisi. Proin sit amet nulla in nunc vestibulum vestibulum. Praesent euismod hendrerit odio, ac commodo neque auctor eget. Morbi iaculis urna mauris, vel vehicula nunc convallis mattis. Aliquam ut pulvinar nisl, sed tincidunt mi.</p>

<p>Morbi ultrices faucibus massa a faucibus. Pellentesque nisi lectus, sodales ac dui sit amet, placerat iaculis risus. Praesent tellus ex, aliquet at tellus ac, consectetur dignissim nisl. Nullam euismod efficitur ex sit amet vehicula. In dignissim augue risus, at commodo lacus porttitor a. Ut pharetra mauris non massa placerat, in imperdiet orci ornare. Duis ac varius nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum ac justo ac sollicitudin. Sed elementum sodales hendrerit. Donec rutrum ligula sit amet massa suscipit, ac bibendum tellus gravida. Integer interdum rutrum eleifend. Nam facilisis elit sit amet est molestie auctor. Nulla sed gravida ipsum.</p>

<p>Fusce cursus nulla at augue molestie pretium. Nam ac porta nisl. Donec dapibus dapibus varius. Etiam imperdiet felis sed auctor condimentum. Vivamus nec ullamcorper augue. Curabitur vel fermentum sapien. Etiam lorem erat, viverra at cursus id, egestas ac augue. Fusce vitae dolor sem. Vestibulum finibus, metus id ultricies bibendum, lacus purus condimentum augue, pretium tempus orci odio vel massa. Aenean non quam scelerisque lorem consectetur vulputate non et metus. Morbi interdum ullamcorper fermentum. In tristique vulputate porttitor. Nam elementum placerat est cursus consequat.</p>

<p>Proin bibendum rhoncus lacus, vitae consectetur magna lobortis quis. Mauris sagittis nunc eu sollicitudin semper. Donec dignissim aliquam turpis, quis ornare leo auctor vitae. Fusce sem lacus, euismod eget magna vitae, mattis condimentum neque. Integer tempor metus nec lacus imperdiet faucibus. Integer placerat sem ut urna feugiat vehicula. Sed tincidunt dolor quis eros convallis, quis convallis est consectetur. Vivamus hendrerit congue tempor. Donec elementum sem blandit nunc convallis, ac blandit quam viverra. In vel nulla tincidunt, placerat diam quis, pulvinar lorem.</p>

<p>Maecenas et tortor ante. Mauris sed ullamcorper nisl. Fusce leo lectus, bibendum sed orci vel, efficitur placerat risus. Pellentesque commodo nisi orci, nec convallis tortor viverra id. In hac habitasse platea dictumst. Nullam at sapien odio. Nulla vitae tristique mi. Phasellus pretium nibh quis tellus egestas, et pulvinar lectus pulvinar. Nam dapibus sit amet enim sed dapibus. Duis luctus, neque quis tincidunt volutpat, arcu erat eleifend arcu, a tincidunt lectus turpis ut felis. Nullam sed justo sagittis, convallis velit sed, gravida odio. Praesent faucibus risus odio. Proin fermentum massa velit, ut vulputate lectus semper non. Nunc lectus sapien, viverra ac ante viverra, vestibulum hendrerit diam.</p>',
    1, 0, 0),
    ('Blog Article 3', '2017-8-11',
      '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at posuere odio. Nam varius leo eget mauris vehicula maximus. Suspendisse vestibulum elementum turpis. Sed eget dui ac ante consequat dapibus eu vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean non quam ligula. Nam ultrices ultricies nunc, id blandit magna iaculis vel. Pellentesque consequat malesuada diam nec lacinia. Donec sagittis purus sed sem luctus, eget tempor nibh pretium. Sed malesuada diam quis nisi gravida gravida. Praesent diam turpis, blandit a dignissim in, ultrices a neque. Nunc lacus ligula, egestas quis placerat sed, maximus eget nisi. Proin sit amet nulla in nunc vestibulum vestibulum. Praesent euismod hendrerit odio, ac commodo neque auctor eget. Morbi iaculis urna mauris, vel vehicula nunc convallis mattis. Aliquam ut pulvinar nisl, sed tincidunt mi.</p>

  <p>Morbi ultrices faucibus massa a faucibus. Pellentesque nisi lectus, sodales ac dui sit amet, placerat iaculis risus. Praesent tellus ex, aliquet at tellus ac, consectetur dignissim nisl. Nullam euismod efficitur ex sit amet vehicula. In dignissim augue risus, at commodo lacus porttitor a. Ut pharetra mauris non massa placerat, in imperdiet orci ornare. Duis ac varius nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum ac justo ac sollicitudin. Sed elementum sodales hendrerit. Donec rutrum ligula sit amet massa suscipit, ac bibendum tellus gravida. Integer interdum rutrum eleifend. Nam facilisis elit sit amet est molestie auctor. Nulla sed gravida ipsum.</p>

  <p>Fusce cursus nulla at augue molestie pretium. Nam ac porta nisl. Donec dapibus dapibus varius. Etiam imperdiet felis sed auctor condimentum. Vivamus nec ullamcorper augue. Curabitur vel fermentum sapien. Etiam lorem erat, viverra at cursus id, egestas ac augue. Fusce vitae dolor sem. Vestibulum finibus, metus id ultricies bibendum, lacus purus condimentum augue, pretium tempus orci odio vel massa. Aenean non quam scelerisque lorem consectetur vulputate non et metus. Morbi interdum ullamcorper fermentum. In tristique vulputate porttitor. Nam elementum placerat est cursus consequat.</p>

  <p>Proin bibendum rhoncus lacus, vitae consectetur magna lobortis quis. Mauris sagittis nunc eu sollicitudin semper. Donec dignissim aliquam turpis, quis ornare leo auctor vitae. Fusce sem lacus, euismod eget magna vitae, mattis condimentum neque. Integer tempor metus nec lacus imperdiet faucibus. Integer placerat sem ut urna feugiat vehicula. Sed tincidunt dolor quis eros convallis, quis convallis est consectetur. Vivamus hendrerit congue tempor. Donec elementum sem blandit nunc convallis, ac blandit quam viverra. In vel nulla tincidunt, placerat diam quis, pulvinar lorem.</p>

  <p>Maecenas et tortor ante. Mauris sed ullamcorper nisl. Fusce leo lectus, bibendum sed orci vel, efficitur placerat risus. Pellentesque commodo nisi orci, nec convallis tortor viverra id. In hac habitasse platea dictumst. Nullam at sapien odio. Nulla vitae tristique mi. Phasellus pretium nibh quis tellus egestas, et pulvinar lectus pulvinar. Nam dapibus sit amet enim sed dapibus. Duis luctus, neque quis tincidunt volutpat, arcu erat eleifend arcu, a tincidunt lectus turpis ut felis. Nullam sed justo sagittis, convallis velit sed, gravida odio. Praesent faucibus risus odio. Proin fermentum massa velit, ut vulputate lectus semper non. Nunc lectus sapien, viverra ac ante viverra, vestibulum hendrerit diam.</p>',
      1, 0, 0),
      ('Blog Article 4', '2017-7-11',
        '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at posuere odio. Nam varius leo eget mauris vehicula maximus. Suspendisse vestibulum elementum turpis. Sed eget dui ac ante consequat dapibus eu vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean non quam ligula. Nam ultrices ultricies nunc, id blandit magna iaculis vel. Pellentesque consequat malesuada diam nec lacinia. Donec sagittis purus sed sem luctus, eget tempor nibh pretium. Sed malesuada diam quis nisi gravida gravida. Praesent diam turpis, blandit a dignissim in, ultrices a neque. Nunc lacus ligula, egestas quis placerat sed, maximus eget nisi. Proin sit amet nulla in nunc vestibulum vestibulum. Praesent euismod hendrerit odio, ac commodo neque auctor eget. Morbi iaculis urna mauris, vel vehicula nunc convallis mattis. Aliquam ut pulvinar nisl, sed tincidunt mi.</p>

    <p>Morbi ultrices faucibus massa a faucibus. Pellentesque nisi lectus, sodales ac dui sit amet, placerat iaculis risus. Praesent tellus ex, aliquet at tellus ac, consectetur dignissim nisl. Nullam euismod efficitur ex sit amet vehicula. In dignissim augue risus, at commodo lacus porttitor a. Ut pharetra mauris non massa placerat, in imperdiet orci ornare. Duis ac varius nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum ac justo ac sollicitudin. Sed elementum sodales hendrerit. Donec rutrum ligula sit amet massa suscipit, ac bibendum tellus gravida. Integer interdum rutrum eleifend. Nam facilisis elit sit amet est molestie auctor. Nulla sed gravida ipsum.</p>

    <p>Fusce cursus nulla at augue molestie pretium. Nam ac porta nisl. Donec dapibus dapibus varius. Etiam imperdiet felis sed auctor condimentum. Vivamus nec ullamcorper augue. Curabitur vel fermentum sapien. Etiam lorem erat, viverra at cursus id, egestas ac augue. Fusce vitae dolor sem. Vestibulum finibus, metus id ultricies bibendum, lacus purus condimentum augue, pretium tempus orci odio vel massa. Aenean non quam scelerisque lorem consectetur vulputate non et metus. Morbi interdum ullamcorper fermentum. In tristique vulputate porttitor. Nam elementum placerat est cursus consequat.</p>

    <p>Proin bibendum rhoncus lacus, vitae consectetur magna lobortis quis. Mauris sagittis nunc eu sollicitudin semper. Donec dignissim aliquam turpis, quis ornare leo auctor vitae. Fusce sem lacus, euismod eget magna vitae, mattis condimentum neque. Integer tempor metus nec lacus imperdiet faucibus. Integer placerat sem ut urna feugiat vehicula. Sed tincidunt dolor quis eros convallis, quis convallis est consectetur. Vivamus hendrerit congue tempor. Donec elementum sem blandit nunc convallis, ac blandit quam viverra. In vel nulla tincidunt, placerat diam quis, pulvinar lorem.</p>

    <p>Maecenas et tortor ante. Mauris sed ullamcorper nisl. Fusce leo lectus, bibendum sed orci vel, efficitur placerat risus. Pellentesque commodo nisi orci, nec convallis tortor viverra id. In hac habitasse platea dictumst. Nullam at sapien odio. Nulla vitae tristique mi. Phasellus pretium nibh quis tellus egestas, et pulvinar lectus pulvinar. Nam dapibus sit amet enim sed dapibus. Duis luctus, neque quis tincidunt volutpat, arcu erat eleifend arcu, a tincidunt lectus turpis ut felis. Nullam sed justo sagittis, convallis velit sed, gravida odio. Praesent faucibus risus odio. Proin fermentum massa velit, ut vulputate lectus semper non. Nunc lectus sapien, viverra ac ante viverra, vestibulum hendrerit diam.</p>',
        1, 0, 0);
