<!-- Google Analytics -->
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-115626803-1', 'auto');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<!-- End Google Analytics -->

<h1>Food Hygiene Ratings</h1>
<div class="left">
  <p>
    2nd year Web and Mobile assignment, which was to create an Android application that queries a server for the hygiene ratings from the Food Standards Agency and presents them in a table and map format. To the right is a screencast of the application running in the Android Studio emulator.
  </p>
  <p>
    Code is here <a href="https://github.com/markbellingham/FoodHygieneRatings"
        onclick="ga(‘send’, {'hitType':'event', 'eventCategory':'code', 'eventAction':'GitHub-Food-Hygiene-Ratings'});">
      <b>https://github.com/markbellingham/FoodHygieneRatings</b>
    </a>
  </p>
  <p>
    The purpose of this app is to query a server which contains information about the food hygiene ratings from the Food Standards Agency for all eateries in the UK. The user can search in three different ways, by GPS co-ordinates, by business name and by postcode. The server returns data about the closest 10 businesses in JSON format. The app then presents the data in table format, using relevant pictures for the ratings. If the search term is too short (minimum 3 characters) or otherwise returns no results, the app displays a relevant error message.
  </p>
  <p>
    When you click on one of the names, the app loads a Google Map showing the locations of all the results of the search, with the one you clicked on highlighted and centred. Sometimes the results in the database generated by the councils place more than one business with exactly the same GPS co-ordinates. In this case the app will generate a random but close by alternative in order to separate them.
  </p>
</div> <!-- ends left -->
<div class="right">
  <center>
    <div class="youtube">
      <iframe class="yt-video" src="https://www.youtube-nocookie.com/embed/4U75zYJ0yS0?rel=0" frameborder="0" allowfullscreen></iframe></iframe>
    </div> <!-- ends youtube -->
  </center>
</div> <!-- ends right -->
